# Generated by Django 4.0.3 on 2022-05-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_product_category_product_condition_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/stores/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='cre_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/stores/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='rate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='refundpolicy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shippingpolicy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
