# Generated by Django 4.0.3 on 2022-05-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_shop_about_shop_banner_shop_cre_policy_shop_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='type1',
        ),
        migrations.AddField(
            model_name='product',
            name='type2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
