# Generated by Django 4.0.3 on 2022-05-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_rename_type_product_type1_product_type2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliatepercentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='altimage1',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='altimage2',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='altimage3',
            field=models.ImageField(blank=True, null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='guarantee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
