# Generated by Django 4.0.3 on 2022-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='altimage1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='altimage2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='altimage3',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/products/'),
        ),
    ]
